services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: ./Dockerfile
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - 8080:8080
    container_name: jenkins
    volumes:
      - jenkins_internal:/var/jenkins_home
      - jenkins_external:/files
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
      - PATH_EXTERNAL=/files
      - PATH_INTERNAL=/var/jenkins_home
      - JENKINS_URL=http://localhost:8080/
    networks:
      project-network:

  mysqldb:
    image: mysql:latest
    restart: always
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: "Root123"
      MYSQL_DATABASE: "project_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "Root123"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      project-network:

  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "9001:9001"
    depends_on:
      - mysqldb
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/project_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Root123
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_SHOW_SQL=true
      - SERVER_PORT=9001
      - PATH_EXTERNAL = /files
      - PATH_INTERNAL = /var/jenkins_home
    networks:
      - project-network
    restart: on-failure

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      project-network:

volumes:
  mysql_db:
  jenkins_internal:
  jenkins_external:

networks:
  project-network:
